### ISSUE TITLE
freqtable: Problem setting row_percent = F or col_percent = F

### ISSUE THREAD

**Issue by Chris-M-P** [davidgohel/rtable#1]
There appears to be an issue setting row_percent = F or col_percent = F in the freqtable function, e.g. this does not work:

    my_freq_table = freqtable(table(mtcars$cyl, mtcars$gear, useNA = "always"), row_percent = F)
    print( my_freq_table )

**Comment by davidgohel** [comment]
Thanks. It should be ok now. 

David

**Comment by Chris-M-P** [comment]
Yes, all fine. Thanks
