### ISSUE TITLE
[feature] Add as.FlexTable method for tabular object

### ISSUE THREAD

**Issue by pcuaron** [davidgohel/rtable#2]
The Duncan Murdoch's `tables::tabular` function/object is great in the sense that it it allows very easy pivots with subtotals (using a nice formula style), something that FlexPivot does not appear to be able to do (or is not reflected in the documentation/examples). But `tables` has no HTML support. Please consider adding support to `as.FlexTable` for the tabular object, it'd make a very powerful tool to be able to combine both packages.

Thanks.

**Comment by davidgohel** [comment]
Hello,

... The function was already existing but I never take time to release it. 
You can have a look on it:

    install_github("davidgohel/rtable", ref = "tabular")

I don't think it's perfect (that's one of the reasons I did not released it before) but it does the job. 
Any feedback is welcome.
 
David
